# Site settings
title: Schuyler Christensen
email: sl_christensen@comcast.net
url: https://slchristensen.github.io/
description: "Schuyler Christensen portfolio page. Resume, portfolio work from UX Design side projects, get in contact. "
keywords: "your keywords, separated by commas"
skills: "Product Manager - Aspiring UX Designer"
meta_author: Christensen Schuyler

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Schuyler Christensen
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://https://github.com/slchristensen
  - title: linkedin
    url: https://www.linkedin.com/in/schuyler-christensen/

# Postal address (add as many lines as necessary)
address:
  - line: Austin, TX 78723

# Credits content
credits: 'Made using <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Bootstrap Theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
